const FavFoodList = [
    'Almonds',
    'Anchovies',
    'Apple Pie',
    'Apples',
    'Applesauce',
    'Apricots',
    'Artichoke',
    'Asparagus',
    'Avocados',
    'Bacon',
    'Bagels',
    'Baklava',
    'Banana Bread',
    'Banana Pudding',
    'Banana Split',
    'Banana',
    'BBQ Pork',
    'Beans',
    'Beets',
    'Biryani',
    'Biscuits',
    'Black Beans',
    'Blackberries',
    'Blueberries',
    'Bok Choy',
    'Bouillabaisse',
    'Bread',
    'Bread Pudding',
    'Broccoli',
    'Brownies',
    'Brussel Sprouts',
    'Burritos',
    'Butternut Squash',
    'Butternut Squash Soup',
    'Cabbage',
    'Cabbage Rolls',
    'Cake',
    'Calzone',
    'Candy bars',
    'Cantaloupe',
    'Caprese Salad',
    'Carrot Cake',
    'Carrots',
    'Cashew Nuts',
    'Catfish',
    'Cauliflower',
    'Caviar',
    'Celery',
    'Cereal',
    'Cesar Salad',
    'Ceviche',
    'Cheese',
    'Cheese Burger',
    'Cheesecake',
    'Cherries',
    'Chicken',
    'Chicken Curry',
    'Chicken Noodle Soup',
    'Chicken Nuggets',
    'Chicken Parmigiana',
    'Chicken Pot Pie',
    'Chicken Tenders',
    'Chicken teriyaki',
    'Chicken Wings',
    'Chicken Wrap',
    'Chili',
    'Chili Dogs',
    'Chimichanga',
    'Chinese Food',
    'Chips',
    'Chocolate Bars',
    'Chocolate Cake',
    'Chocolate Chip Cookies',
    'Cinnamon Rolls',
    'Clam Chowder',
    'Clementines',
    'Collard Greens',
    'Cookies',
    'Corn',
    'Cornbread',
    'Cottage Cheese',
    'Couscous',
    'Crab',
    'Crackers',
    'Cranberries',
    'Crepes',
    'Croissants',
    'Cucumbers',
    'Cupcakes',
    'Dates',
    'Deviled Eggs',
    'Donuts',
    'Doritos',
    'Dried Fruit',
    'Duck',
    'Edamame',
    'Egg Salad Sandwich',
    'Eggplant',
    'Eggplant Parmesan',
    'Eggs',
    'Eggs Benedict',
    'Empanada',
    'Enchilada',
    'Ethiopian Food',
    'Fajitas',
    'Fast food',
    'Fettucini Alfredo',
    'Figs',
    'Fish',
    'Fish and Chips',
    'Fish Curry',
    'Fish Tacos',
    'French Fries',
    'French Toast',
    'Fried Chicken',
    'Fried Egg Sandwich',
    'Fried Rice',
    'Frozen Yogurt',
    'Fudge',
    'Garlic Bread',
    'Gazpacho',
    'Gelato',
    'Goulash',
    'Grapefruits',
    'Grapes',
    'Greek food',
    'Greek Salad',
    'Green Bean Casserole',
    'Green Beans',
    'Grilled Cheese',
    'Guacamole and chips',
    'Guava',
    'Gyro Sandwhich',
    'Halibut',
    'Ham',
    'Hamburger',
    'Honeydew',
    'Hot Dogs',
    'Hummus',
    'Ice Cream',
    'Ice Cream Sundae',
    'Indian food',
    'Italian food',
    'Japanese food',
    'Kale',
    'Kimchi',
    'Kiwi',
    'Korean food',
    'Lamb',
    'Lentils',
    'Lobster',
    'Lobster Roll',
    'Lychees',
    'Macaroni and Cheese',
    'Mango',
    'Mashed Potatoes',
    'Meatball Sub',
    'Meatballs',
    'Mexican food',
    'Mozzarella sticks',
    'Mustard Greens',
    'Nachos',
    'Nectarines',
    'New York Cheesecake',
    'Noodles',
    'Nuts',
    'Oatmeal',
    'Octopus',
    'Okra',
    'Omelette',
    'Onion Rings',
    'Oranges',
    'Oysters Rockefeller',
    'Pad Thai',
    'Pancakes',
    'Panna Cotta',
    'Passionfruit',
    'Pasta',
    'Peaches',
    'Pecan Pie',
    'Pecans',
    'Philly Cheesesteaks',
    'Pho',
    'Pie',
    'Pierogies',
    'Pineapple',
    'Pita Bread',
    'Pizza',
    'Plums',
    'Polish sausages',
    'Pomegranates',
    'Popcorn',
    'Pork Chops',
    'Pork Tenderloin',
    'Porridge',
    'Potato Chips',
    'Potato Salad',
    'Potatoes',
    'Prawns',
    'Pretzels',
    'Profiteroles',
    'Prunes',
    'Pudding',
    'Pulled Pork',
    'Pumpkin Pie',
    'Quesadilla',
    'Quiche',
    'Quinoa',
    'Raisins',
    'Ramen Noodles',
    'Raspberries',
    'Ravioli',
    'Red Beans and Rice',
    'Ribs',
    'Rice',
    'Rice Cakes',
    'Roast Beef',
    'Roast Beef Sandwich',
    'Salad',
    'Salmon',
    'Samosa',
    'Sandwiches',
    'Sardines',
    'Scallops',
    'Shrimp',
    'Shrimp and Grits',
    'Shrimp Scampi',
    'Sole',
    'Soup',
    'Spaghetti',
    'Spanish food',
    'Spinach',
    'Squash',
    'Steak',
    'Strawberries',
    'Stuffed Peppers',
    'Submarine sandwiches',
    'Sugar snap peas',
    'Sushi',
    'Sweet Potatoes',
    'Swiss Chard',
    'Tacos',
    'Tamales',
    'Tangerines',
    'Tater Tots',
    'Thai Curry',
    'Thai food',
    'Tilapia',
    'Tiramisu',
    'Tofu',
    'Tomato Soup',
    'Tomatoes',
    'Tuna Salad',
    'Turkey',
    'Veggie Burger',
    'Venison',
    'Waffles',
    'Walnuts',
    'Watermelon',
    'Yogurt',
    'Zucchini',
];

export default FavFoodList;